global:
  team:
    name: infrastructure-developer-experience
    slack: ask-ide
    repo:
      name: colorapp
      owner: PayFit
colorapp:
  enabled: true
  image:
    repository: ghcr.io/bapturp/colorapp-go
    tag: '' # to be overridden by ArgoCD Application
  serverPort: 8080
  resources:
    requests:
      memory: 100Mi
      cpu: 10m
    limits:
      memory: 100Mi
  env:
    COLOR: blue
  nodeSelector:
    node.payfit.net/role: applications
  tolerations:
    - key: node.payfit.net/role
      operator: Equal
      value: applications
      effect: NoSchedule
